const DATE_FORMAT = /^-?\d{1,4}(?:-(?:0[1-9]|1[0-2])(?:-(?:0[1-9]|[1-2]\d|3[0-1]))?)?$/
const EVENT_TOOLTIP_TEXT = 'Map is centered on the country where the event took place.'
const TIME_FORMAT = 'HH:mm'

const EVENT_NAME = 'EVENT'
const EVENT_CATEGORY_NAME = 'EVENT_CATEGORY'
const HISTORICAL_FIGURE_NAME = 'HISTORICAL_FIGURE'
const HISTORICAL_STATE_NAME = 'HISTORICAL_STATE'
const PRESENT_COUNTRY_NAME = 'PRESENT_COUNTRY'

export {
    DATE_FORMAT, EVENT_TOOLTIP_TEXT, TIME_FORMAT,
    EVENT_NAME, EVENT_CATEGORY_NAME, HISTORICAL_FIGURE_NAME, HISTORICAL_STATE_NAME, PRESENT_COUNTRY_NAME
}