const DEV_API_EVENTS_APP_BASE_URL = 'http://localhost:8000/api/events/'

const EVENT_CATEGORIES_SECTION = 'event-categories'
const HISTORICAL_EVENTS_SECTION = 'events'
const HISTORICAL_FIGURES_SECTION = 'figures'
const HISTORICAL_STATES_SECTION = 'historical-states'
const PRESENT_COUNTRIES_SECTION = 'present-countries'

const EVENT_CATEGORIES_ENDPOINT = 'event-categories/'
const HISTORICAL_FIGURES_ENDPOINT = 'figures/'
const HISTORICAL_STATES_ENDPOINT = 'historical-states/'
const PRESENT_COUNTRIES_ENDPOINT = 'present-countries/'

const EVENT_CATEGORIES_FULL_URL =
  DEV_API_EVENTS_APP_BASE_URL + EVENT_CATEGORIES_ENDPOINT
const FIGURES_FULL_URL =
  DEV_API_EVENTS_APP_BASE_URL + HISTORICAL_FIGURES_ENDPOINT
const HISTORICAL_STATES_FULL_URL =
  DEV_API_EVENTS_APP_BASE_URL + HISTORICAL_STATES_ENDPOINT
const PRESENT_COUNTRIES_FULL_URL =
  DEV_API_EVENTS_APP_BASE_URL + PRESENT_COUNTRIES_ENDPOINT

export {
  DEV_API_EVENTS_APP_BASE_URL,
  EVENT_CATEGORIES_SECTION,
  HISTORICAL_EVENTS_SECTION,
  HISTORICAL_FIGURES_SECTION,
  HISTORICAL_STATES_SECTION,
  PRESENT_COUNTRIES_SECTION,
  EVENT_CATEGORIES_FULL_URL,
  FIGURES_FULL_URL,
  HISTORICAL_STATES_FULL_URL,
  PRESENT_COUNTRIES_FULL_URL
}
