export const DEV_API_EVENTS_APP_BASE_URL = "http://localhost:8000/api/events/"


export const HISTORICAL_EVENTS_ENDPOINT = "events/"
export const HISTORICAL_FIGURES_ENDPOINT = "figures/"

const EVENT_CATEGORIES_ENDPOINT = "event-categories/"
const HISTORICAL_STATES_ENDPOINT = "historical-states/"
const PRESENT_COUNTRIES_ENDPOINT = "present-countries/"


export const FIGURES_FULL_URL = DEV_API_EVENTS_APP_BASE_URL + HISTORICAL_FIGURES_ENDPOINT
export const EVENT_CATEGORIES_FULL_URL = DEV_API_EVENTS_APP_BASE_URL + EVENT_CATEGORIES_ENDPOINT
export const HISTORICAL_STATES_FULL_URL = DEV_API_EVENTS_APP_BASE_URL + HISTORICAL_STATES_ENDPOINT
export const PRESENT_COUNTRIES_FULL_URL = DEV_API_EVENTS_APP_BASE_URL + PRESENT_COUNTRIES_ENDPOINT