# Generated by Django 4.1.2 on 2022-11-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_presentcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='presentCountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.presentcountry'),
        ),
    ]
