# Generated by Django 4.1.2 on 2022-11-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_historicalevent_presentcountryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dateFrom', models.CharField(max_length=15)),
                ('dateTo', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='approximateRealLocation',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='historicalStateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.historicalstate'),
        ),
    ]
