# Generated by Django 4.1.2 on 2022-11-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_historicalstate_datefrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='historicalStateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.historicalstate'),
        ),
    ]
