# Generated by Django 4.1.2 on 2022-11-29 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_historicalevent_historicalstateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='date',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='dateFrom',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='dateTo',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
    ]
