# Generated by Django 4.1.2 on 2022-11-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_historicalfigure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalfigure',
            old_name='historicalStateId',
            new_name='birthHistoricalStateId',
        ),
    ]
