# Generated by Django 4.1.2 on 2022-12-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventcategory_createdat_eventcategory_updatedat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFigureRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('historicalEventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.historicalevent')),
                ('historicalFigureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.historicalfigure')),
                ('historicalFigureRoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.historicalfigurerole')),
            ],
        ),
    ]
