# Generated by Django 4.1.2 on 2022-12-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventfigurerole'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventfigurerole',
            constraint=models.UniqueConstraint(fields=('historicalEventId', 'historicalFigureId', 'historicalFigureRoleId'), name='unique_event_figure_role'),
        ),
    ]
