# Generated by Django 4.1.2 on 2023-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventfigurerole_unique_event_figure_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfigure',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='historicalfigurerole',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='historicalstate',
            name='flagUrl',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='presentcountry',
            name='flagUrl',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
