# Generated by Django 4.1.2 on 2023-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_historicalfigure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstate',
            name='flagUrl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='presentcountry',
            name='flagUrl',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
