# Generated by Django 4.1.2 on 2024-01-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_rename_presentcountryid_historicalfigure_birthpresentcountryid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfigure',
            name='deathHistoricalStateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deathHistoricalState', to='events.historicalstate'),
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='deathPresentCountryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deathPresentCountry', to='events.presentcountry'),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='birthHistoricalStateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthHistoricalState', to='events.historicalstate'),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='birthPresentCountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthPresentCountry', to='events.presentcountry'),
        ),
    ]
