# Generated by Django 5.0.3 on 2024-03-29 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_historicalfigure_deathhistoricalstateid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalfigure',
            name='deathDate',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalfigurerole',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='dateFrom',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='dateTo',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='flagUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='presentcountry',
            name='flagUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
