# Generated by Django 5.0.3 on 2024-03-31 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_historicalfigure_deathdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='eventCategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventcategory'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='historicalStateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.historicalstate'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='presentCountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.presentcountry'),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='birthHistoricalStateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birthHistoricalState', to='events.historicalstate'),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='birthPresentCountryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birthPresentCountry', to='events.presentcountry'),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='deathHistoricalStateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deathHistoricalState', to='events.historicalstate'),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='deathPresentCountryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deathPresentCountry', to='events.presentcountry'),
        ),
    ]
