# Generated by Django 5.0.3 on 2024-04-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_historicalevent_eventcategoryid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'ordering': ['name']},
        ),
    ]
