# Generated by Django 5.0.3 on 2024-10-03 13:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventcategory_createdby_eventcategory_updatedby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStatePresentCountryPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('dateFrom', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')])),
                ('dateTo', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')])),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('historicalState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.historicalstate')),
                ('presentCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.presentcountry')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='historicalstatepresentcountryperiod',
            constraint=models.UniqueConstraint(fields=('historicalState', 'presentCountry', 'dateFrom', 'dateTo'), name='unique_historical_state_present_country_period'),
        ),
    ]
