# Generated by Django 5.0.3 on 2024-10-03 13:19

from django.db import migrations

def transfer_data_intermediary_table_historical_states_present_countries(apps, schema_editor):
    HistoricalState = apps.get_model('events', 'HistoricalState')
    HistoricalStatePresentCountryPeriod = apps.get_model('events', 'HistoricalStatePresentCountryPeriod')

    for historical_state in HistoricalState.objects.all():
        for present_country in historical_state.presentCountries.all():
            HistoricalStatePresentCountryPeriod.objects.create(
                historicalState=historical_state,
                presentCountry=present_country,
                dateFrom=None,
                dateTo=None,
                createdBy=historical_state.createdBy,
                updatedBy=historical_state.updatedBy
            )

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_historicalstatepresentcountryperiod_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_data_intermediary_table_historical_states_present_countries)
    ]
