# Generated by Django 5.0.3 on 2024-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20241003_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstate',
            name='presentCountries',
            field=models.ManyToManyField(related_name='presentCountries', through='events.HistoricalStatePresentCountryPeriod', to='events.presentcountry'),
        ),
    ]
