# Generated by Django 5.0.3 on 2025-01-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_rename_createdat_eventcategory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstate',
            old_name='dateTo',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='historicalstate',
            old_name='flagUrl',
            new_name='flag_url',
        ),
        migrations.RenameField(
            model_name='historicalstate',
            old_name='dateFrom',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='historicalstate',
            name='presentCountries',
        ),
        migrations.AddField(
            model_name='historicalstate',
            name='present_countries',
            field=models.ManyToManyField(related_name='present_countries', through='events.HistoricalStatePresentCountryPeriod', to='events.presentcountry'),
        ),
    ]
