# Generated by Django 5.0.3 on 2025-01-03 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_rename_dateto_historicalstate_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historicalstatepresentcountryperiod',
            name='unique_historical_state_present_country_period',
        ),
        migrations.RenameField(
            model_name='historicalstatepresentcountryperiod',
            old_name='dateTo',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='historicalstatepresentcountryperiod',
            old_name='historicalState',
            new_name='historical_state',
        ),
        migrations.RenameField(
            model_name='historicalstatepresentcountryperiod',
            old_name='presentCountry',
            new_name='present_country',
        ),
        migrations.RenameField(
            model_name='historicalstatepresentcountryperiod',
            old_name='dateFrom',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='presentcountry',
            old_name='flagUrl',
            new_name='flag_url',
        ),
        migrations.AddConstraint(
            model_name='historicalstatepresentcountryperiod',
            constraint=models.UniqueConstraint(fields=('historical_state', 'present_country', 'start_date', 'end_date'), name='unique_historical_state_present_country_period'),
        ),
    ]
