# Generated by Django 5.0.3 on 2025-01-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_remove_historicalstatepresentcountryperiod_unique_historical_state_present_country_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalfigure',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='historicalfigure',
            old_name='deathDate',
            new_name='death_date',
        ),
        migrations.RemoveField(
            model_name='historicalfigure',
            name='birthHistoricalStateId',
        ),
        migrations.RemoveField(
            model_name='historicalfigure',
            name='birthPresentCountryId',
        ),
        migrations.RemoveField(
            model_name='historicalfigure',
            name='deathHistoricalStateId',
        ),
        migrations.RemoveField(
            model_name='historicalfigure',
            name='deathPresentCountryId',
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='birth_historical_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='birth_historical_state', to='events.historicalstate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='birth_present_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='birth_present_country', to='events.presentcountry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='death_historical_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='death_historical_state', to='events.historicalstate'),
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='death_present_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='death_present_country', to='events.presentcountry'),
        ),
    ]
