# Generated by Django 5.0.3 on 2025-01-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_rename_birthdate_historicalfigure_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalevent',
            old_name='approximateRealLocation',
            new_name='approximate_location',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='eventCategoryId',
            new_name='event_category',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='historicalStateId',
            new_name='historical_state',
        ),
        migrations.RenameField(
            model_name='historicalevent',
            old_name='presentCountryId',
            new_name='present_country',
        ),
    ]
