# Generated by Django 5.0.3 on 2025-01-03 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_rename_approximatereallocation_historicalevent_approximate_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventfigurerole',
            name='unique_event_figure_role',
        ),
        migrations.RenameField(
            model_name='eventfigurerole',
            old_name='historicalEventId',
            new_name='historical_event',
        ),
        migrations.RenameField(
            model_name='eventfigurerole',
            old_name='historicalFigureId',
            new_name='historical_figure',
        ),
        migrations.RenameField(
            model_name='eventfigurerole',
            old_name='historicalFigureRoleId',
            new_name='historical_figure_role',
        ),
        migrations.AddConstraint(
            model_name='eventfigurerole',
            constraint=models.UniqueConstraint(fields=('historical_event', 'historical_figure', 'historical_figure_role'), name='unique_event_figure_role'),
        ),
    ]
