# Generated by Django 5.0.3 on 2025-01-09 17:56

import django.core.validators
import events.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_remove_eventfigurerole_unique_event_figure_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='date',
            field=events.fields.CustomDateField(max_length=15, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='birth_date',
            field=events.fields.CustomDateField(max_length=15, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='death_date',
            field=events.fields.CustomDateField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='end_date',
            field=events.fields.CustomDateField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='start_date',
            field=events.fields.CustomDateField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalstatepresentcountryperiod',
            name='end_date',
            field=events.fields.CustomDateField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalstatepresentcountryperiod',
            name='start_date',
            field=events.fields.CustomDateField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^-?\\d{1,4}$|^-?\\d{1,4}-\\d{2}$|^-?\\d{1,4}-\\d{2}-\\d{2}$', message='The date must have one of the following formats: YYYY, YYYY-MM, YYYY-MM-DD. Negative years are allowed.')]),
        ),
    ]
