# Generated by Django 5.0.3 on 2025-01-09 18:02

import django.core.validators
import events.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_alter_historicalevent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalevent',
            name='latitude',
            field=events.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='longitude',
            field=events.fields.CoordinateField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
